Delay flex counters stats init for faster boot time, Option 2
shlomibitton/sonic-swss pull request #2
Opened 2021-01-28 15:00 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**What I did**
Add two shared objects to sync between PortsOrch and FlexCounterOrch.
As long the polling counters are not enabled, all flex counters information will stored internally on PortsOrch.
When the PORT counter is enabled, all the data will be processed by the FlexCounterOrch.

**Why I did it**
Creating flex counters objects on the DB will trigger 'SYNCD' to access the HW for query statistics capabilities.
This HW access takes time and will be better to finish boot before doing this (mainly for fast-reboot but good to have in general).
The flex counters are not crucial at boot time, we can delay it to the end of the boot process.

**How I verified it**
Reboot a switch and observer the flex counters DB populated after counters are enabled.

**Details if related**

2021-02-08 15:22 UTC, stepanblyschak requested changes
General comments:
- Please avoid creating additional global state
- Not sure this PR covers PG, QUEUE, WATERMARK counters
- Caching values for setCounterIdList function arguments is not justified

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/flexcounterorch.h
> +#define PORT_STAT_FLEX_COUNTER_POLLING_INTERVAL_MS     1000
What this new constant stands for?

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/orchdaemon.cpp
> +    port_stat_list = new vector<tuple<sai_object_id_t, enum CounterType, unordered_set<string>>>;
These seems unnecessary memory allocations while it can reside in static memory.

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/flexcounterorch.cpp
> +extern std::vector<std::tuple<sai_object_id_t, enum CounterType, std::unordered_set<std::string>>> *port_stat_list;
This seems to be a state for an object, could you please make this state local to FlexCounterOrch object instead of making them global?

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/flexcounterorch.cpp
> +                            port_stat_manager.setCounterIdList(std::get<0>(port_stat), std::get<1>(port_stat), std::get<2>(port_stat));
unclear what are the values behind indexes 0, 1, 2

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                    port_stat_manager.setCounterIdList(p.m_port_id, CounterType::PORT, counter_stats);
How this port_stat_manager is related to the same variable in FlexCounterOrch. Seems there is the same code in two places.

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                    (*port_stat_list).push_back(make_tuple(p.m_port_id, CounterType::PORT, counter_stats));
Not sure why we need to cache this into a list. Can't FlexCounterOrch just call PortsOrch public method to setCounterIdList(). That will resolve my previous comment as well.

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                    (*port_stat_list).push_back(make_tuple(p.m_port_id, CounterType::PORT, counter_stats));
```suggestion
                    port_stat_list->push_back(make_tuple(p.m_port_id, CounterType::PORT, counter_stats));
```

2021-02-08 15:22 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                (*port_stat_list).erase(port_stat);
```suggestion
                port_state = port_stat_list->erase(port_stat);
```

2021-02-08 15:22 UTC, stepanblyschak commented on tests/mock_tests/portsorch_ut.cpp
> +            port_stat_list = new vector<tuple<sai_object_id_t, enum CounterType, unordered_set<string>>>;
They are always nullptr sine you put them on static storage

2021-02-11 14:58 UTC, shlomibitton commented on orchagent/flexcounterorch.cpp
> +                    if((key == "PORT") && (value == "enable"))
Fixed

2021-02-11 15:32 UTC, stepanblyschak requested changes

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/flexcounterorch.cpp
> +                    if((key == "PORT") && (value == "enable"))
Aren't there defines for these constatns? in several places: "PORT", "PORT_BUFFER_DROP", "QUEUE"?

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/flexcounterorch.h
> +    bool m_port_buffer_drop_counter_enabled;
```suggestion
    bool m_port_counter_enabled{false};
    bool m_port_buffer_drop_counter_enabled{false};
```
And you can remove their initialization in ctor

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                FlexCounterOrch* flex_counters_orch = gDirectory.get<FlexCounterOrch*>();
```suggestion
                auto flex_counters_orch = gDirectory.get<FlexCounterOrch*>();
```

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +    FlexCounterOrch* flex_counters_orch = gDirectory.get<FlexCounterOrch*>();
```suggestion
    auto flex_counters_orch = gDirectory.get<FlexCounterOrch*>();
```

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +        port_buffer_drop_stat_manager.clearCounterIdList(p.m_port_id);
This is added statement, why do you need it?

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +        SWSS_LOG_NOTICE("PORT_BUFFER_DROP_STAT enabled and installed");
I think there are other indications that counters were enabled in the log, so this might be too verbose.
Maybe lover it to INFO?

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.h
> +    void InstallFlexCounters(string type);
Use camelCaseStyle

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.h
> +    void InstallFlexCounters(string type);
```suggestion
    void InstallFlexCounters(const string &type);
```

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.h
> +    void InstallFlexCounters(string type);
Why not to have it on par with generateQueueMap, generatePriorityGroupMap, etc?

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                if (flex_counters_orch->getPortCountersState())
A comment is crucial to understand who and when will generate port counters map

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +            counter_stats.emplace(sai_serialize_port_stat(it));
This is duplicate from initPort

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +            if (port.second.m_init == true)
If this is called before m_init is set to true, who will do port_stat_manager.setCounterIdList?

2021-02-11 15:32 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +            if (port.second.m_init == true)
```suggestion
            if (port.second.m_init)
```

2021-02-11 15:51 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +        port_buffer_drop_stat_manager.clearCounterIdList(p.m_port_id);
This is the solution for DPB
when the port is created we delay the "setCounterIdList", but if we split the port before the counter is enabled we will try to do "clearCounterIdList" with invalid 'p.m_port_id'
this is to avoid such case.

2021-02-11 15:59 UTC, shlomibitton commented on orchagent/portsorch.h
> +    void InstallFlexCounters(string type);
Do you mean use the same name style for the function?

2021-02-11 16:00 UTC, stepanblyschak commented on orchagent/portsorch.h
> +    void InstallFlexCounters(string type);
I suggest to create:
generatePortCounterMap and generatePortBufferDropCounterMap on par with others.

2021-02-11 16:02 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +        port_buffer_drop_stat_manager.clearCounterIdList(p.m_port_id);
I do not see a call to port_buffer_drop_stat_manager.clearCounterIdList before your change in deinitPort

2021-02-11 16:05 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +            counter_stats.emplace(sai_serialize_port_stat(it));
It must be AFAIK, this set is local on initPort function.
The new function will create this set only once for all counters.

2021-02-11 16:06 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +        port_buffer_drop_stat_manager.clearCounterIdList(p.m_port_id);
you are correct, I removed it.

2021-02-11 16:11 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +            counter_stats.emplace(sai_serialize_port_stat(it));
I mean it is a code duplicate, let's utilize this in a single function

2021-02-11 16:12 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +            counter_stats.emplace(sai_serialize_port_stat(it));
got you, will do

2021-02-11 16:23 UTC, shlomibitton commented on orchagent/flexcounterorch.cpp
> +                    if((key == "PORT") && (value == "enable"))
there are defines like "PORT_STAT_COUNTER" for example but couldn't find "PORT" or any of the others

2021-02-11 16:50 UTC, stepanblyschak commented on orchagent/flexcounterorch.cpp
> +                    if((key == "PORT") && (value == "enable"))
Could you please create them?

2021-02-11 17:08 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +            if (port.second.m_init == true)
This is to sync between initPort and deInitPort functions.
if initPort will run and delay one counter for example, it will set 'm_init' to true and no counter will be installed.
if we remove this port before enable the counter, 'deInitPort' will run and keep this port in the internal data structure but the 'm_init' flag will change to false.
In this case after the counter is enabled we would like to skip this port counter installation since it is not a valid port anymore.

2021-02-11 17:16 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +            if (port.second.m_init == true)
Right after deInit() there is port removal from https://github.com/shlomibitton/sonic-swss/blob/aab2fdfeec13888b8d9db86696bf75cdbace9321/orchagent/portsorch.cpp#L2641.

Do you think there can be call to InitFlexCounter call in between those two?

2021-02-11 19:36 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +            if (port.second.m_init == true)
When thinking about it, I don't think so
If the port is removed so it won't be on 'm_portList' so it is not needed.
If the execution will take place first, when getting to doPortTask it will be removed right after.
Removed it.

2021-02-15 12:31 UTC, stepanblyschak approved these changes

2021-02-18 09:20 UTC, closed without merging