Add flex counters unit-test
shlomibitton/sonic-swss pull request #3
Opened 2021-03-24 20:34 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

2021-03-31 13:25 UTC, stepanblyschak requested changes
Could you please define the scope of this test? IMO it is intended to test that counters are delayed but this test verifies that enable/disable logic which I thought is already implemented as part of each counter group test?

2021-03-31 13:25 UTC, stepanblyschak commented on tests/test_flex_counters.py
> +        for counter_entry in counters_keys.items():
Suggest to unpack tuple right away in this for loop instead of using indexes counter_entry[1] counter_entry[2].

2021-03-31 13:25 UTC, stepanblyschak commented on tests/test_flex_counters.py
> +        time.sleep(2)
Sleep(2) or better to wait till counters maps are generated?

2021-03-31 13:25 UTC, stepanblyschak commented on tests/test_flex_counters.py
> +        except Exception as e:
Why do we need to wrap it in try..except if we are asserting in except block anyway? Same comment applies to several places.

2021-03-31 13:25 UTC, stepanblyschak commented on tests/test_flex_counters.py
> +            assert False, "Failed to write/read from DB, exception: {}".format(str(e))
This is pretty much duplicated code, have you considered to use test parametrization (https://docs.pytest.org/en/stable/parametrize.html)?

2021-04-01 13:28 UTC, shlomibitton commented on tests/test_flex_counters.py
> +        for counter_entry in counters_keys.items():
Done.

2021-04-01 13:28 UTC, shlomibitton commented on tests/test_flex_counters.py
> +        except Exception as e:
you are right, removed this wrap.

2021-04-01 13:28 UTC, shlomibitton commented on tests/test_flex_counters.py
> +            assert False, "Failed to write/read from DB, exception: {}".format(str(e))
Done.

2021-04-05 17:04 UTC, closed without merging