[Counters] Add new functionality to configure port queues creation
shlomibitton/sonic-swss pull request #9
Opened 2021-12-30 09:27 UTC by shlomibitton

**What I did**

Add a new mechanism to filter out unwanted port queues counters with a new DB scheme.
This is to allow the user to choose which queue counters to create and poll and not always do it to max queues.
if there is no configuration for some port, by default UC queues will be created and MC queues will not.

**Why I did it**

Currently in SONiC there is no way to configure which port queues to create.
This feature allow the user to configure which port queues to create with a new DB scheme.
On portsOrch, when creating a new port, there are two SAI API calls related to queue counters:
•	Get number of supported queues by the port (will return max always).
•	Get a list of queues by the returned size.
When the flex counter is enabled, orchagent will go over the returned queue list per port and create counters by this list.
This will always create the max number of queues supported by the platform.
The new configuration will filter the unwanted queues returned by the SAI API call and thus skip the creation of these queue counters.

**How I verified it**

Check after enabling the counters, if configured queue counters created in Counters DB according to the configurations.
For unconfigured port queue counters, only 0-7 (UC queues) created.

**Details if related**

2021-12-30 10:20 UTC, stepanblyschak requested changes

2021-12-30 10:20 UTC, stepanblyschak commented on orchagent/flexcounterorch.cpp
> +                queueStream >> queueIndex;
stringstream does not let you know if the string is successfully parsed. We have a utility function in swss common:
```suggestion
                int queueIndex{};
                try {
                     queueIndex = swss::to_int<int>(queue);
                } catch (std::invalid_argument) {
                      continue;
                }
```

2021-12-30 10:20 UTC, stepanblyschak commented on orchagent/portsorch.h
> +#define MAX_MC_QUEUE_INDEX 15
Lets put these defines togather with MIN_QUEUE_INDEX and MAX_QUEUE_INDEX  ?

2021-12-30 10:20 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +    auto flex_counters_orch = gDirectory.get<FlexCounterOrch*>();
```suggestion
    auto flexCounterOrch = gDirectory.get<FlexCounterOrch*>();
```

2021-12-30 10:20 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +    bool queuesConfigured = flex_counters_orch->getQueueConfigurations(port.m_alias, queueStates);
What if user configured CFG_PORTS_QUEUES_STATE_TABLE_NAME in runtime?

2021-12-30 10:20 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +void PortsOrch::initQueuesState(bool *queuesState)
It seems that the queueState is an object. It can be default constructed (```initQueuesState```), constructed from DB data (```getQueueConfigurations```) and provides an access method to check the queue state, so at least 2 ctors and 1 method.
I suggest to create a ```class``` for it and encapsulate the internal representation (array of bools).

2021-12-31 09:42 UTC, shlomibitton commented on orchagent/flexcounterorch.cpp
> +                    SWSS_LOG_WARN("Unvalid counter queue index [%d] configured for port [%s]", queueIndex, portName.c_str());
Done

2021-12-31 09:43 UTC, shlomibitton commented on orchagent/flexcounterorch.cpp
> +bool FlexCounterOrch::isQueueIndexValid(int index)
Done

2021-12-31 09:43 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +    bool *queueStates = new bool[MAX_QUEUE_NUMBER];
Done

2021-12-31 09:43 UTC, shlomibitton commented on orchagent/flexcounterorch.cpp
> +    for (auto& portField : portFields)
Done

2021-12-31 09:43 UTC, shlomibitton commented on orchagent/flexcounterorch.cpp
> +            for (auto& queue : configQueuesState)
Done

2021-12-31 09:43 UTC, shlomibitton commented on orchagent/flexcounterorch.cpp
> +                queueStream >> queueIndex;
Done

2021-12-31 09:44 UTC, shlomibitton commented on orchagent/portsorch.h
> +#define MAX_MC_QUEUE_INDEX 15
I kept MAX_QUEUE_NUMBER in FlexCounterOrch since I had some compilation issues, moved all the rest to PortsOrch

2021-12-31 09:44 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +    auto flex_counters_orch = gDirectory.get<FlexCounterOrch*>();
Done

2021-12-31 09:46 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +    bool queuesConfigured = flex_counters_orch->getQueueConfigurations(port.m_alias, queueStates);
As discussed, no CLI is required so no runtime is required.
Still need to check with arch if DPB should be supported.
Consider a new feature request to configure all counters objects.

2021-12-31 09:46 UTC, shlomibitton commented on orchagent/portsorch.cpp
> +void PortsOrch::initQueuesState(bool *queuesState)
Done

2021-12-31 11:06 UTC, stepanblyschak requested changes

2021-12-31 11:06 UTC, stepanblyschak commented on orchagent/flexcounterorch.cpp
> +                }
Makes more sense to use unsigned version:

```c++
template <typename T>
T to_uint(const std::string &str, T min = std::numeric_limits<T>::min(), T max = std::numeric_limits<T>::max())
```

Also, these functions already provide min/max bounds check, so I suggest:
```suggestion
                std::uint8_t queueIndex{};
                try {
                    queueIndex = to_int<std::uint8_t>(queue, MIN_QUEUE_INDEX, MAX_QUEUE_INDEX);
                } catch (std::invalid_argument const& e) {
                    SWSS_LOG_WARN("Invalid queue index [%s]", queue.c_str());
                    continue;
                }
```

2022-01-04 17:26 UTC, closed without merging